### ISSUE TITLE
deal with fastqc output with user-provided adapters

### ISSUE THREAD

**Issue by nrode** [timflutre/quantgen#8]
Would it be posible to change the stopifnot condition l271-273 in utilis_fatsqc.R so that the script can also deal with fastqc outputs whith user-provided adapter sequences?
Thanks,

N.

**Comment by timflutre** [comment]
done, see the [commit](https://github.com/timflutre/quantgen/commit/f8b861d0f81dffd6f27f10fe563706998174a8f3), let me know if there is a problem
